name: library_scanner_flutter_example
description: A Flutter example demonstrating how to configure the library_scanner_domain package.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  library_scanner_domain:
    path: ../..
  dio: ^5.4.0
  fpdart: ^1.2.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true