name: datastore_isar
description: Isar datastore implementation for the library scanner domain. Proves clean architecture with ACID transactions.
version: 2.1.2
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0-0 <4.0.0"

dependencies:
  isar: ^3.1.0+1
  fpdart: ^1.2.0
  id_registry: ^1.0.1
  id_logging:
    git: https://github.com/staylorx/id_logging.git
  uuid: ^4.5.2

  domain_contracts: any
  domain_entities: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  mocktail: ^1.0.4
  matcher: ^0.12.18
  path: ^1.9.1
