name: dataservice_filtering
description: Data service implementations for filtering books and authors.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0-0 <4.0.0"

dependencies:
  fpdart: ^1.2.0
  id_logging:
    git: https://github.com/staylorx/id_logging.git
  domain_contracts: any
  domain_entities: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6