name: library_scanner_core
description: The core layer for the library scanner app.
version: 2.1.2
# repository: https://github.com/my_org/my_repo
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0-0 <4.0.0"

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.7
  fpdart: ^1.2.0
  yaml: ^3.1.2
  yaml_writer: ^2.1.0
  uuid: ^4.5.2
  id_registry: ^1.0.1
  id_logging:
    git: https://github.com/staylorx/id_logging.git
  slugify_string: ^2.0.0

  domain_contracts: any
  domain_usecases: any
  domain_entities: any
  datastore_sembast: any
  dataservice_filtering: any
  datastore_files: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  mocktail: ^1.0.4
  matcher: ^0.12.18
  benchmark_harness: ^2.3.0
  path: ^1.9.1
